# Eigenvalues and Eigenvectors

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

Let A be a sqaure matrix. A non-zero vector v is an eigenvector for A with eigenvalue  if


Rearranging the equation, we see v is a solution of homogenous system of equations

where I is the identity matrix of size n. Eigenvalues of A are roots of the characteristic polynomial

The function `scipy.linalg.eig` computes eigenvalues and eigenvectors of a square matrix 

In [2]:
# Let's consider a simple example
A = np.array([[1,0],[0,-1]])
print(A)

[[ 1  0]
 [ 0 -1]]


In [3]:
# The function la.eig returns eigenvalues and eigenvectors as tuples
eigvals, eigvecs = la.eig(A)

In [4]:
# The eigenvalues of A are
print(eigvals)

[ 1.+0.j -1.+0.j]


In [5]:
# The eigenvectors of A are
print(eigvecs)

[[1. 0.]
 [0. 1.]]


In [6]:
# If we know the eigenvalues are real numbers, A is symmetrics, then we use the method `.real` to convert into real numbers
print(eigvals.real)

[ 1. -1.]


## Symmetric Matrices
Symmetric matrix is a square matrix that is qual to its taranspose



- The entries of a symmetric matrix are symmetrics with respect to the main diagonal
- eigenvalues are real
- eigenvectors are always orthogonal

In [7]:
A = np.array([[1, 7, 3],
              [7, 4, -5],
              [3, -5, 6]])
print(A)

[[ 1  7  3]
 [ 7  4 -5]
 [ 3 -5  6]]


In [8]:
# Transpose of A
print(A.T)

[[ 1  7  3]
 [ 7  4 -5]
 [ 3 -5  6]]


In [9]:
eigvals, eigvecs = la.eig(A)

In [10]:
# Eigenvalues have zero imaginary part
print(eigvals)

[-7.00792852+0.j  7.03594585+0.j 10.97198268+0.j]


In [11]:
print(eigvecs)

[[ 0.68415383 -0.62878419 -0.36954564]
 [-0.61391034 -0.22292725 -0.75724338]
 [-0.39376087 -0.74493885  0.53853365]]


In [12]:
# Check that eigenvectors are orthogonal
# The dot product of eigenvectors  and  is zero 
v1 = eigvecs[:,0] # First column is the first eigenvector
v2 = eigvecs[:,1] # Second column is the second eigenvector
print(v1 @ v2)


0.0
